namespace Imageboard;

public interface IId
{
}

public readonly record struct BoardId(string Value) : IId
{
    public static explicit operator BoardId(string value) => new(value);
    public static implicit operator string(BoardId id) => id.Value;

    public override string ToString() => Value;
}

public readonly record struct ThreadId(long Value) : IId
{
    public static explicit operator ThreadId(long value) => new(value);
    public static implicit operator long(ThreadId id) => id.Value;

    public override string ToString() => Value.ToString();
}

public readonly record struct CommentId(long Value) : IId
{
    public static explicit operator CommentId(long value) => new(value);
    public static implicit operator long(CommentId id) => id.Value;

    public override string ToString() => Value.ToString();
}

public readonly record struct RawCommentContent(string Value)
{
    public static explicit operator RawCommentContent(string value) => new(value);
    public static implicit operator string(RawCommentContent id) => id.Value;

    public override string ToString() => Value;
}

/// <summary>
/// A comprehensive list of all threads+attributes on a board.
/// </summary>
public class Catalog
{
    public required Board Board;
    public required Page[] Pages;

    public class Page
    {
        /// <summary>
        /// Page number in the catalog.
        /// </summary>
        public int Id;
        
        public required Thread[] Threads;
    }
}

public class Board
{
    /// <summary>
    /// Board ID.
    /// Example: 'g'.
    /// </summary>
    public required BoardId Id;

    /// <summary>
    /// Board title.
    /// Example: "Technology".
    /// </summary>
    public required string Title;

    /// <summary>
    /// Board category.
    /// Example: "Adult".
    /// </summary>
    public string? Category;

    /// <summary>
    /// Board description.
    /// </summary>
    public string? Description;

    /// <summary>
    /// The primary language that's used on the board.
    /// Example: "en".
    ///
    /// For example, `kohlchan.net` imageboard is a German one
    /// but it also has a separate `/ru/` board for Russian-speaking users.
    /// </summary>
    public string? Language;

    /// <summary>
    /// Is this board "Not Safe for Work" aka "NSFW"?
    /// </summary>
    public required bool ExplicitContent;

    /// <summary>
    /// Board statistics.
    /// </summary>
    public StatsData? Stats;

    public struct StatsData
    {
        /// <summary>
        /// "Comments posted per hour" stats for this board.
        /// </summary>
        public int? CommentsPerHour;

        /// <summary>
        /// "Comments posted per day" stats for this board.
        /// </summary>
        public int? CommentsPerDay;

        /// <summary>
        /// "Unique comment posters per day" stats for this board.
        /// </summary>
        public int? UniquePostersPerDay;
    }
}

public enum AttachmentType
{
    /// <summary>
    /// .PNG, .JPG, etc.
    /// </summary>
    Image,

    /// <summary>
    /// .GIF
    /// </summary>
    ImageAnimated,

    /// <summary>
    /// .WEBM, .MP4, etc.
    /// </summary>
    Video,

    /// <summary>
    /// .MP3, .WAV, .OGG, etc.
    /// </summary>
    Audio,

    /// <summary>
    /// Another other file type.
    /// </summary>
    File,
    
    /// <summary>
    /// Invalid file format.
    /// </summary>
    Null,
}

public class Thread
{
    /// <summary>
    /// Thread ID.
    /// Same as the id of the first comment.
    /// </summary>
    public required ThreadId Id;

    /// <summary>
    /// Board ID.
    /// Example: 'g'.
    /// </summary>
    public required BoardId BoardId;

    /// <summary>
    /// If true, <see cref="Comments"/> will be null, as we don't need them.
    /// Used to list threads quickly from the Catalog.
    /// </summary>
    public required bool Summary;

    /// <summary>
    /// Thread title ("subject").
    /// </summary>
    public string? Title;

    /// <summary>
    /// If the thread has no <see cref="Title"/>, then <see cref="AutogeneratedTitle"/> is generated from the thread's
    /// "original comment" content.
    /// </summary>
    public string? AutogeneratedTitle;

    /// <summary>
    /// The date on which the thread was created.
    ///
    /// <remarks>
    /// This is absent in the "get threads list" API response of the of `lynxchan` engine which is a bug.
    /// But seems like they don't want to fix it.
    /// </remarks>
    /// </summary>
    public DateTime? CreatedAt;

    /// <summary>
    /// "Last Modified Date", usually including:
    /// Posting new comments, deleting existing comments, sticky/closed status changes.
    /// 
    /// <remarks>
    /// Is usually present on all imageboards in "get threads list" API response,
    /// but not in "get thread comments" API response.
    /// </remarks>
    /// </summary>
    public DateTime? UpdatedAt;

    /// <summary>
    /// If this was an incremental "get thread" API request, <see cref="AfterCommentId"/> could potentially contain
    /// the ID of the latest comment that was skipped when returning a list of 'comments' in this thread.
    /// </summary>
    public CommentId? AfterCommentId;

    /// <summary>
    /// Number of comments in this thread.
    /// (Including the main comment of the thread).
    /// </summary>
    public required int CommentsCount;

    /// <summary>
    /// Number of attachments in this thread.
    /// (Including the attachments of the main comment of the thread).
    /// </summary>
    public required int AttachmentsCount;

    /// <summary>
    /// Number of attachments in this thread.
    /// (NOT including the attachments of the main comment of the thread).
    /// </summary>
    public required int CommentAttachmentsCount;

    /// <summary>
    /// Unique poster IP address subnets count.
    /// Only present in "get thread" API response.
    /// </summary>
    public int? UniquePosterCount;

    /// <summary>
    /// The list of comments in this thread.
    /// (Including the main comment of the thread).
    /// <remarks>
    /// This will be <see langword="null"/> if <see cref="Summary"/> is set to <see langword="true"/>.
    /// </remarks>
    /// </summary>
    public Comment[]? Comments;

    /// <summary>
    /// Is this thread "sticky" ("pinned") ("on top of others").
    /// </summary>
    public required bool Pinned;

    /// <summary>
    /// Is this thread "locked", i.e. doesn't allow any new comments.
    /// </summary>
    public required bool Locked;

    /// <summary>
    /// On imageboards, threads "expire" due to being pushed off the last page of a board because there haven't been new replies.
    /// On some boards, such "expired" threads are moved into an "archive" rather than just being deleted immediately.
    /// Eventually, a thread is deleted from the archive too.
    /// <remarks>
    /// If a thread is archived, then it's locked too (by definition).
    /// </remarks>
    /// </summary>
    public bool? Archived;
    
    /// <summary>
    /// If <see cref="Archived"/> is <see langword="true"/>, then <see cref="ArchivedDate"/> might be defined.
    /// Maybe. Not all boards support this. So always check it!
    /// </summary>
    public DateTime? ArchivedDate;

    /// <summary>
    /// Was the "bump limit" reached for this thread already.
    /// <remarks>
    /// Is <see langword="false"/> when the thread is <see cref="Pinned"/> or "trimming", because such threads don't expire.
    /// </remarks>
    /// </summary>
    public bool? BumpLimitReached;

    /// <summary>
    /// Custom spoiler ID (if custom spoilers are used on the board).
    /// For example, `4chan.org` has this feature.
    /// </summary>
    public int? CustomSpoilerId;

    /// <summary>
    /// If this thread is marked by any "tags", this is going to be a list of those.
    /// "Tags" could be used when searching for threads.
    /// </summary>
    public string[]? Tags;

    /// <summary>
    /// The comment content of the first post.
    /// </summary>
    public required RawCommentContent? RawCommentContent;
    
    /// <summary>
    /// The attachment of the first post.
    /// </summary>
    public required Attachment? Attachment;
}

public class Comment
{
    /// <summary>
    /// Comment ID.
    /// </summary>
    public required CommentId Id;
    
    /// <summary>
    /// Thread ID the comment is part of.
    /// </summary>
    public required ThreadId ThreadId;
    
    /// <summary>
    /// Board ID the comment is part of.
    /// </summary>
    public required BoardId BoardId;

    /// <summary>
    /// Comment title ("subject").
    /// </summary>
    public string? Title;
    
    /// <summary>
    /// The date on which the comment was created.
    /// </summary>
    public required DateTime CreatedAt;
    
    /// <summary>
    /// "Last Modified Date" of the comment.
    ///
    /// I guess it includes all possible comment "modification" actions like editing comment text, deleting attachments, etc.
    /// Is present on "modified" comments in "get thread comments" API response of the `lynxchan` engine.
    /// </summary>
    public DateTime? UpdatedAt;

    /// <summary>
    /// Tells if the comment author is the thread author. ("OP") or ("Original Poster")
    /// This feature is used on `2ch.hk` imageboard:
    /// 2ch.hk` provides means for "original posters" to identify themselves
    /// when replying in their own threads with a previously set "OP" cookie.
    /// </summary>
    public bool? AuthorIsThreadAuthor;
    
    /// <summary>
    /// Some imageboards identify their users by a hash of their IP address subnet on some of their boards (for example, all imageboards do that on `/pol/` boards).
    /// On `8ch` and `lynxchan` it's a three-byte hex string (like "d1e8f1"), on `4chan` it's a 8-character case-sensitive alphanumeric string (like "Bg9BS7Xl").
    ///
    /// Even when a thread uses `authorIds` for its comments, not all of them might have it. For example, on `4chan`,
    /// users with "capcodes" (moderators, etc.) don't have an `authorId`.
    /// </summary>
    public string? AuthorId;

    /// <summary>
    /// If <see cref="AuthorId"/> is present, then it's converted into a HEX color.
    /// </summary>
    public string? AuthorIdColorHex;

    /// <summary>
    /// Comment author name.
    /// </summary>
    public string? AuthorName;
    
    /// <summary>
    /// If this flag is <see langword="true"/> then it means that <see cref="AuthorName"/> is an equivalent of an <see cref="AuthorId"/>.
    /// For example, `2ch.hk` autogenerates `authorName` based on IP address subnet hash on the `/po/` board.
    /// </summary>
    /// <returns></returns>
    public bool? AuthorNameIsId;

    /// <summary>
    /// Comment author's email address.
    /// </summary>
    public string? AuthorEmail;

    /// <summary>
    /// Comment author's "tripcode".
    /// https://en.wikipedia.org/wiki/Imageboard
    /// </summary>
    public string? AuthorTripcode;

    /// <summary>
    /// A two-letter ISO country code (or "ZZ" for Anonymized").
    /// Imageboards usually show poster flags on `/int/` boards, for example.
    /// </summary>
    public string? AuthorCountry;
        
    /// <summary>
    /// Some imageboards allow comment author icons on some boards.
    ///
    /// For example, `kohlchan.net` shows user icons on `/int/` board.
    /// Author icon examples in this case: "UA", "RU-MOW", "TEXAS", "PROXYFAG", etc.
    /// `authorIconUrl` is `/.static/flags/${authorIconId}.png`.
    /// `authorIconName` examples in this case: "Ukraine", "Moscow", "Texas", "Proxy", etc.
    ///
    /// Also, `2ch.hk` allows icons for posts on various boards like `/po/`.
    /// Author icon examples in this case: "nya", "liber", "comm", "libertar", etc.
    /// `authorIconUrl` is `/icons/logos/${authorIconId}.png`.
    /// `authorIconName` examples in this case: "Nya", "Либерализм", "Коммунизм", "Либертарианство", etc.
    /// </summary>
    public string? AuthorIconUrl;
    public string? AuthorIconName;

    /// <summary>
    /// If the comment was posted by a "priviliged" user then it's gonna be the role of the comment author.
    /// Examples: "administrator", "moderator".
    /// </summary>
    public string? AuthorRole;

    /// <summary>
    /// `8ch.net (8kun.top)` and `lynxchan` have "global adiministrators"
    /// and "board administrators", and "global moderators"
    /// and "board moderators", so `authorRoleScope` is gonna be
    /// "board" for a "board administrator" or "board moderator".
    /// </summary>
    public string? AuthorRoleScope;

    /// <summary>
    /// If <see langword="true"/>, then the author was banned for the message.
    /// </summary>
    public bool? AuthorBanned;

    /// <summary>
    /// Reason why the author was banned in <see cref="AuthorBanned"/> (if provided).
    /// </summary>
    public string? AuthorBannedReason;

    /// <summary>
    /// If `true` then it means that the author has been verified to be the one who they're claiming to be.
    /// The same as the "verified" checkmark on celebrities pages on social media like YouTube or Instagram.
    /// </summary>
    public bool? AuthorVerified;

    /// <summary>
    /// If this comment was posted with a "sage".
    /// https://knowyourmeme.com/memes/sage
    /// </summary>
    public bool? Sage;

    /// <summary>
    /// Upvotes count for this comment.
    /// If comment rating is enabled, <see cref="Upvotes"/> could or could not be present.
    /// </summary>
    public int? Upvotes;
    
    /// <summary>
    /// Upvotes count for this comment.
    /// If comment rating is enabled, <see cref="Downvotes"/> could or could not be present.
    /// </summary>
    public int? Downvotes;

    /// <summary>
    /// Raw HTML data of the comment.
    /// </summary>
    public RawCommentContent? RawCommentContent;

    /// <summary>
    /// The IDs of the comments to which this <see cref="Comment"/> replies.
    /// If some of the replies have been deleted, their IDs will not be present in this list.
    /// </summary>
    public CommentId[]? InReplyToIds;
    
    /// <summary>
    /// If this <see cref="Comment"/> replies to some other comments that have been deleted,
    /// then this is gonna be the list of IDs of such deleted comments.
    /// </summary>
    public CommentId[]? InReplyToIdsRemoved;

    /// <summary>
    /// The actual comments to which this <see cref="Comment"/> replies.
    /// </summary>
    public Comment[]? InReplyTo;

    /// <summary>
    /// The IDs of the comments that replies to this <see cref="Comment"/>.
    /// </summary>
    public CommentId[]? ReplyIds;

    /// <summary>
    /// The actual comments that replies to this <see cref="Comment"/>.
    /// </summary>
    public Comment[]? Replies;

    /// <summary>
    /// Comment attachment.
    /// </summary>
    public Attachment? Attachment;
}

public class Attachment
{
    /// <summary>
    /// URL to the attachment.
    /// </summary>
    public required string BigUrl;

    /// <summary>
    /// URL to the small (preview) version of the attachment.
    /// </summary>
    public required string SmallUrl;
    
    /// <summary>
    /// Extension of the attachment.
    /// </summary>
    public required string Ext;

    /// <summary>
    /// Type of the attachment.
    /// </summary>
    public required AttachmentType Type;
}